### ISSUE TITLE
Unable to find configuration file - October Build #334

### ISSUE THREAD

**Issue by rajakhoury** [SaifurRahmanMohsin/Txt#16] opened 2016-05-17 15:32 UTC
The plugin ( v 1.0.7) throws an error with the latest October CMS build 334

Robots -> New Robot -> Error
Unable to find configuration file @/plugins/mohsin/txt/models/directive/fields.yaml defined for Owl\FormWidgets\HasMany\Widget.
D:\xampp\htdocs\site\modules\system\traits\ConfigMaker.php line 63

**Comment by SaifurRahmanMohsin** [comment] 2016-05-18 02:09
Hey thanks for reporting this. Will check

**Comment by Silarn** [comment] 2016-06-02 18:12
The issue is within Owl\HasMany - the ConfigMaker.php prepends the createConfig parameter with the '@', but the proper syntax is now a '~'.

Making this edit fixes the error for me, however clicking on the '+Add _____' links doesn't seem to do anything.

**Comment by mateocode** [comment] 2016-08-10 18:31
I too am getting the same error/issue as @rajakhoury and my vendors directory isn't blocked in my htaccess file. Suggestions?

**Comment by SaifurRahmanMohsin** [comment] 2016-08-10 19:04
I’ve requested the author of the original dependency to update the repo. But for now a temporary fix would be to change

```
$relationship = $this->makeConfig("@/plugins/$parts[0]/$parts[1]/models/$parts[3]/fields.yaml");
```
to
```
$relationship = $this->makeConfig(plugins_path()."/$parts[0]/$parts[1]/models/$parts[3]/fields.yaml");
```

In the `plugins/mohsin/rating/vendor/owl/hasmany/Widget.php` file.

I’m closing this issue now as this fix should solve it. Do report if the issue or any other issue exists after making the fix, I will reopen and see what’s wrong then.

**Closed by SaifurRahmanMohsin** 2016-08-10 19:04 UTC

**Comment by Silarn** [comment] 2016-08-10 19:29
I'd just say that until this is fixed in the parent repo (which has been inactive for some time), making the solution harder to find might not be ideal.

**Comment by SaifurRahmanMohsin** [comment] 2016-08-10 19:38
The alternative is that I include the hasmany widget as part of this plugin.

**Comment by zakir1929** [comment] 2019-01-09 13:40
This widget is not working with October CMS 446 build.

![image](https://user-images.githubusercontent.com/16069667/50902902-40426180-1442-11e9-96ac-5f0c4cf1f03b.png)
